# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  uatBatchDir: '"C:\Program Files\Epic Games\UE_4.25\Engine\Build\BatchFiles\"'
  majorVersion: 0
  minorVersion: 1

name: '$(majorVersion).$(minorVersion).$(Rev:r)'

jobs:
- job: buildPlugin

  pool: 'default'

  displayName: Build Plugin Job

  steps:
  - task: CmdLine@2
    displayName: 'Run UAT'
    inputs:
      script: RunUAT.bat BuildPlugin -Plugin="$(Build.SourcesDirectory)/Plugins/JiraPlugin/JiraPlugin.uplugin" -Package="$(Build.SourcesDirectory)/Build/JiraPlugin" -CreateSubFolder
      workingDirectory: $(uatBatchDir)


