# Copyright TD Technologies. All rights reserved.

trigger:
- master

variables:
  uatBatchDir: '"C:\Program Files\Epic Games\UE_4.25\Engine\Build\BatchFiles\"'
  majorVersion: 0
  minorVersion: 1

name: 'BlueprintsForJira_$(majorVersion).$(minorVersion).$(Rev:r)'

jobs:
- job: buildPlugin
  pool: 'default'
  displayName: Build Plugin Job
  steps:
  - task: CmdLine@2
    displayName: 'Run UAT'
    inputs:
      script: RunUAT.bat BuildPlugin -Plugin="$(Build.SourcesDirectory)\Plugins\JiraPlugin\JiraPlugin.uplugin" -Package="$(Build.SourcesDirectory)\Build\JiraPlugin" -CreateSubFolder -VS2019
      workingDirectory: $(uatBatchDir)
  - task: CopyFiles@2
    displayName: 'Copy Build to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\Build\JiraPlugin'
      Contents: |
        *.uplugin
        Binaries\**\?(*.modules|*.dll)
        Resources\**
      TargetFolder: '$(Build.BinariesDirectory)'
      CleanTargetFolder: true
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
      replaceExistingArchive: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish to nas.tdtek.net' 
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '$(Build.BuildNumber)'
      publishLocation: 'FilePath'
      TargetPath: '\\nas.tdtek.net\builds\ue\'
