# Copyright TD Technologies. All rights reserved.

trigger:
- master

variables:
  uatBatchDir: '"C:\Program Files\Epic Games\UE_4.25\Engine\Build\BatchFiles\"'
  majorVersion: 0
  minorVersion: 1

name: 'BlueprintsForJira_$(majorVersion).$(minorVersion).$(Rev:r)'

jobs:
- job: executeTestProject
  pool: 'default'
  displayName: Execute Tests Job
  steps:
  - checkout: self
    submodules: true
  - task: CmdLine@2
    displayName: 'Run Tests'
    inputs:
      script: UE4Editor.exe $(Build.SourcesDirectory)\JiraEnginePlugin.uproject -ExecCmds="Automation RunTests FTEST_FunctionalTests" -unattended -nopause -testexit="Automation Test Queue Empty" -ReportOutputPath="$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber)-TestLog"
      workingDirectory: 'C:\Program Files\Epic Games\UE_4.25\Engine\Binaries\Win64\'
  - task: PowerShell@2
    displayName: 'Convert Unreal Results to VSTest (.trx) Format'
    inputs:
      filePath: '$(Build.SourcesDirectory)\DevOps-Convert-UnrealTests\Convert-UnrealTests.ps1'
      arguments: '"$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber)-TestLog" "$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber)-TestLog.trx"'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '*.trx'
      searchFolder: '$(Build.ArtifactStagingDirectory)'
      failTaskOnFailedTests: true
      testRunTitle: '$(Build.BuildNumber)'
      publishRunAttachments: false

- job: buildPlugin
  pool: 'default'
  dependsOn: executeTestProject
  displayName: Build Plugin Job
  steps:
  - task: CmdLine@2
    displayName: 'Run UAT'
    inputs:
      script: RunUAT.bat BuildPlugin -Plugin="$(Build.SourcesDirectory)\Plugins\JiraPlugin\JiraPlugin.uplugin" -Package="$(Build.BinariesDirectory)" -CreateSubFolder -VS2019 -TargetPlatforms=Win32+Win64+HoloLens
      workingDirectory: '$(uatBatchDir)'
  - task: CopyFiles@2
    displayName: 'Perpare Build Files'
    inputs:
      SourceFolder: '$(Build.BinariesDirectory)'
      Contents: |
        *.uplugin
        Binaries\**\?(*.modules|*.dll)
        Resources\**
      TargetFolder: '$(Build.BinariesDirectory)\_Release'
      CleanTargetFolder: true
  - task: CopyFiles@2
    displayName: 'Perpare Debug Files'
    inputs:
      SourceFolder: '$(Build.BinariesDirectory)'
      Contents: |
        *.uplugin
        Binaries\**\?(*.modules|*.dll|*.pch)
        Resources\**
      TargetFolder: '$(Build.BinariesDirectory)\_Debug'
      CleanTargetFolder: true
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)\_Release'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
      replaceExistingArchive: true
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)\_Debug'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber)-d.zip'
      replaceExistingArchive: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish to nas.tdtek.net' 
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '$(Build.BuildNumber)'
      publishLocation: 'FilePath'
      TargetPath: '\\nas.tdtek.net\builds\ue\'
